#!/bin/bash
input="$1"
cd $( dirname "$0" )
function help_msg() {
echo AU216 Virtual Private Network Collection - v1.0
echo
echo "Usage: ./installer [option]"
echo
echo "Options:"
echo "-i, --install         Install AU216-VPN."
echo "-v, --version         Display version."
echo "-h, --help            Display this message and exit."
echo
}
case $input in
	"-i"|"--install")
	echo Installing AU216-VPN...
	cp dat/au216vpn /usr/local/bin
	chmod +x /usr/local/bin/au216vpn
	cp dat/au216vpn /usr/bin
	chmod +x /usr/bin/au216vpn
	cp -r au216vpn /opt
	chmod +x /opt/au216vpn/dat/vpn
	sleep 3
	echo
	echo Done.
	echo
	echo "You can run 'au216vpn' to start the VPN client."
	echo "P.S. You can reuse this installer!"
	echo
	;;
	"-v"|"--version")
	echo AU216 Virtual Private Network Collection - v1.0
	echo "Copyright (c) 2018 by Anonymous User 216"
	echo
	;;
	""|"-h"|"--help")
	help_msg
	;;
	*)
	echo
	echo -e "\e[1;31mYour choice was not recognized.\e[0m"
	echo
	help_msg
esac
