#!/bin/bash
TOA="\e[0m" # No color
wbold="\e[1;37m" # White-bold
wcol="\e[0;37m" # White
rbold="\e[1;31m" # Red-bold
gbold="\e[1;32m" # Green-bold
ybold="\e[1;33m" # Yellow-bold
err_count=0
cat_vpn="$(cat /opt/au216vpn/dat/vpn)"
serv_path="/opt/au216vpn/servers/"
openvpnStatus=""
if [ "$(cat /opt/au216vpn/dat/ver/ver)" = "ver" ] # Verify ver-file
then
	echo "au216vpn: ver: verification file exists"
	sleep 1
else
	echo "au216vpn: ver: verification file missing"
	echo -e "${gbold}[*]${wcol} Not required, continuing...${TOA}"
	sleep 1.8
fi
if [ "${cat_vpn:34:27}" = "AkdiicHhebbcllaokcnhwbbqhxj" ] # Verify certificate
then
	echo "au216vpn: vpn: file certificate intact, usable"
	sleep 1
else
	echo "au216vpn: vpn: file corrupt or unusable"
	echo -e "${rbold}[!]${wcol} This file must be intact for the VPN client to work properly, please reinstall this package to reset it${TOA}"
	sleep 5.8
	err_count=$((err_count+1))
fi
if [ -e $serv_path"canada1.ovpn" ] && [ -e $serv_path"france1.ovpn" ] && [ -e $serv_path"germany1.ovpn" ] &&
	[ -e $serv_path"us1.ovpn" ] && [ -e $serv_path"us2.ovpn" ] && [ -e $serv_path"germany4.ovpn" ] && [ -e $serv_path"poland226.ovpn" ] &&
	[ -e $serv_path"canada222.ovpn" ]
then
	echo "au216vpn: servers intact"
	sleep 1
else
	echo "au216vpn: server(s) missing"
	echo -e "${ybold}[~]${wcol} One or more VPNBook servers are missing, not required but highly recommended${TOA}"
	sleep 5.8
fi
dpkg -s openvpn &> /dev/null && echo "au216vpn: openvpn: app installed"; sleep 1 || openvpnStatus="notInstalled"
if [[ $openvpnStatus == "notInstalled" ]]
then
	echo "au216vpn: openvpn: app not installed"
	echo -e "${rbold}[!]${wcol} This app is required for the VPN client to work, please install this package${TOA}"
	err_count=$((err_count+1))
	sleep 5.8
fi
if [ $err_count = 0 ]
then
	if [ "$( cat /opt/au216vpn/dat/dep_msg )" = "req-ver-msg: 1" ]
	then
		echo
		echo "Congratulations! Your au216vpn configuration is setup properly!"
		echo "(You can stop seeing this message in 99.5)"
		sleep 3.3
	fi
elif [ $err_count = 1 ]
then
	echo
	echo "Your au216vpn configuration has 1 error."
else
	echo
	echo "Your au216vpn configuration has $err_count errors."
fi
