#!/bin/bash
TOA="\e[0m" # No color
wbold="\e[1;37m" # White-bold
wcol="\e[0;37m" # White
rbold="\e[1;31m" # Red-bold
gbold="\e[1;32m" # Green-bold
ybold="\e[1;33m" # Yellow-bold
err_count=0
cat_vpn="$(cat /opt/au216vpn/dat/vpn)"
pvpns="/opt/au216vpn/servers/protonvpn/"
vpnbs="/opt/au216vpn/servers/vpnbook/"
if [ -e /opt/au216vpn ] # Verify root folder existence
then
	echo "au216vpn: root folder exists"
	sleep 1
else
	echo "au216vpn: root folder missing"
	echo -e "${rbold}[!]${wcol} This folder is required for the VPN client to work properly, it is recommended you install it${TOA}"
	sleep 3.8
	err_count=$((err_count+1))
fi
if [ "$(cat /opt/au216vpn/dat/ver/ver)" = "ver" ] # Verify ver-file
then
	echo "au216vpn: ver: verification file exists"
	sleep 1
else
	echo "au216vpn: ver: verification file missing"
	echo -e "${gbold}[*]${wcol} Not required, continuing...${TOA}"
	sleep 1.8
fi
if [ "${cat_vpn:34:27}" = "AkdiicHhebbcllaokcnhwbbqhxj" ] # Verify certificate
then
	echo "au216vpn: vpn: file certificate intact, usable"
	sleep 1
else
	echo "au216vpn: vpn: file corrupt or unusable"
	echo -e "${rbold}[!]${wcol} This file must be intact for the VPN client to work properly, please reinstall this package to reset it${TOA}"
	sleep 3.8
	err_count=$((err_count+1))
fi
if [ -e $pvpns"japan1.ovpn" ] && [ -e $pvpns"japan2.ovpn" ] && [ -e $pvpns"netherlands1.ovpn" ] && [ -e $pvpns"netherlands2.ovpn" ] && [ -e $pvpns"us1.ovpn" ] && [ -e $pvpns"us2.ovpn" ] # Verify ProtonVPN server existence
then
	echo "au216vpn: servers: protonvpn servers intact"
	sleep 1
else
	echo "au216vpn: servers: protonvpn server(s) missing"
	echo -e "${ybold}[~]${wcol} One or more ProtonVPN servers are missing, not required but highly recommended${TOA}"
	sleep 3.8
fi
if [ -e $vpnbs"canada1.ovpn" ] && [ -e $vpnbs"france1.ovpn" ] && [ -e $vpnbs"germany1.ovpn" ] && [ -e $vpnbs"romania1.ovpn" ] && [ -e $vpnbs"romania2.ovpn" ] && [ -e $vpnbs"us3.ovpn" ] && [ -e $vpnbs"us4.ovpn" ]
then
	echo "au216vpn: servers: vpnbook servers intact"
	sleep 1
else
	echo "au216vpn: servers: vpnbook server(s) missing"
	echo -e "${ybold}[~]${wcol} One or more VPNBook servers are missing, not required but highly recommended${TOA}"
	sleep 3.8
fi
if [ $err_count = 0 ]
then
	if [ "$( cat /opt/au216vpn/dat/dep_msg )" = "req-ver-msg: 1" ]
	then
		echo
		echo "Congratulations! Your au216vpn configuration is setup properly!"
		echo "(You can stop seeing this message in 99.5)"
		sleep 3.3
	fi
elif [ $err_count = 1 ]
then
	echo
	echo "Your au216vpn configuration has 1 error."
else
	echo
	echo "Your au216vpn configuration has $err_count errors."
fi
