#!/bin/bash
#Verify-certificate:
#AkdiicHhebbcllaokcnhwbbqhxj
#
#     DO NOT MESS WITH THE VERIFY-CERTIFICATE (above)! This will ruin the client!
#
TOA="\e[0m" # No color
wbold="\e[1;37m" # White-bold
wcol="\e[0;37m" # White
rbold="\e[1;31m" # Red-bold
gbold="\e[1;32m" # Green-bold
ybold="\e[1;33m" # Yellow-bold
err_count=0
cat_vpn="$(cat /opt/au216vpn/dat/vpn)"
serv_path="/opt/au216vpn/servers/"
vpnbook_password="${rbold}[MUST BE ENTERED VIA 99.4]${wcol}"
function vpnbook_login() {
	echo
	echo Username: vpnbook
	echo -e "Password: $vpnbook_password (Server not working? Update the password [99.4])"
	echo
}
location=""
function redir_loca() {
	if [ $location = "add_options" ]
	then
		clear
		add_options
		testing
	else
		serv_select
		testing
	fi
}
wtrmrk="\e[1;36m" # Cyan-bold (WaTeRMaRK color)
cd "/opt/au216vpn" &> /dev/null && echo -n "" || eval "echo 'ERR: Program folder missing, program unusable, exiting...'; exit"
chmod +x dat/chk_dep
dat/chk_dep
clear
echo -e "${wcol}Welcome! Loading..."
sleep 2
clear
echo
echo -e "${wtrmrk}######################################################################"
echo "######################################################################"
echo "##          _    _ ___  __   __  _  _____   __      _______  _   _  ##"
echo "##     /\  | |  | |__ \/_ | / / ( )/ ____|  \ \    / /  __ \| \ | | ##"
echo "##    /  \ | |  | |  ) || |/ /_ |/| (___     \ \  / /| |__) |  \| | ##"
echo "##   / /\ \| |  | | / / | | '_ \   \___ \     \ \/ / |  ___/| . \` | ##"
echo "##  / ____ \ |__| |/ /_ | | (_) |  ____) |     \  /  | |    | |\  | ##"
echo "## /_/    \_\____/|____||_|\___/  |_____/       \/   |_|    |_| \_| ##"
echo "##                                                                  ##"
echo "######################################################################"
echo "### Anonymous User 216's Virtual Private Network Collection - v1.1-pre ###"
echo "######################################################################"
echo 
echo -n -e "${wcol}Press ENTER to continue..." && read null_input
echo




function serv_select() { # Server select menu
location="serv_select"
uses=(11 12 21 31 41 51)
for x in ${uses[*]}; do
	usescount=$(cat 'uses/'$x)
	if [ $usescount -lt 21 ]
	then
		declare "s${x}=\e[1;32m$usescount$wcol"
	elif [ $usescount -lt 41 ]
	then
		declare "s${x}=\e[1;33m$usescount$wcol"
	else
		declare "s${x}=\e[1;31m$usescount$wcol"
	fi
done
clear
echo -e "${wtrmrk}These are the available servers:"
echo 
echo -e "${wbold}(1) Virginia, United States${wcol}"
echo -e "	(1.1) Server #1 -$s11-"
echo -e "	(1.2) Server #2 -$s12-"
echo -e "${wbold}(2) Montreal, Canada${wcol}"
echo -e "	(2.1) Server #1 -$s21-"
echo -e "${wbold}(3) Frankfurt, Germany${wcol}"
echo -e "	(3.1) Server #1 -$s31-"
echo -e "${wbold}(4) Roubaix, France${wcol}"
echo -e "	(4.1) Server #1 -$s41-"
echo -e "${wbold}(5) Warsaw, Poland${wcol}"
echo -e "	(5.1) Server #1 -$s51-"
echo
echo -e "${wbold}(99) Additional Options${wcol}"
echo -e "	(99.1) Reset all usage values"
echo -e "	(99.2) Edit one usage value"
echo -e "	(99.3) Disconnect an existing connection"
echo -e "	(99.4) Update the VPNBook password"
echo -e "	(99.5) View dependency message at start"
echo -e "	(99.6) Exit the program"
echo
echo "Please choose an option."
echo -n "> " && read serv_pick
}
serv_select




function testing() { # Testing value options
if [ $serv_pick = "99" ] && [ $location != "add_options" ]
then
	function add_options() { # Additional options menu
	location="add_options"
	echo
	echo -e "${wbold}Additional Options:${wcol}"
	echo "(99.1) Reset all usage values"
	echo "(99.2) Edit one usage value"
	echo "(99.3) Disconnect an existing connection"
	echo "(99.4) Update the VPNBook password"
	echo "(99.5) View dependency message at start"
	echo "(99.6) Exit the program"
	echo "(99.7) Back to the previous menu"
	echo
	echo -n "> " && read serv_pick
	}
	add_options
fi
case $serv_pick in
	"99.1") 
	for x in ${uses[*]}; do
	echo 0 > "uses/"$x
	done
	sleep 1
	echo
	echo "Done."
	sleep 1
	redir_loca
	;;
	"99.2")
	function serv_edit() {
	echo
	echo "Server number?"
	echo -n "> " && read serv_del
	case $serv_del in
		"1.1"|"1.2"|"2.1"|"3.1"|"4.1"|"5.1")
		echo
		echo "Are you adding, subtracting, or clearing the value of Server $serv_del? (A/S/C)"
		serv_del="${serv_del:0:1}${serv_del:2:2}"
		echo -n "> " && read serv_delop
		case $serv_delop in
			"a"|"A")
			echo
			echo "By how much?"
			read -p "> " serv_del_amount
			echo $(($(cat "uses/$serv_del")+$serv_del_amount)) > uses/$serv_del
			sleep 1
			echo
			echo "Done."
			sleep 1
			redir_loca
			;;
			"s"|"S")
			echo
			echo "By how much?"
			read -p "> " serv_del_amount
			echo $(($(cat "uses/$serv_del")-$serv_del_amount)) > uses/$serv_del
			sleep 1
			echo
			echo "Done."
			sleep 1
			redir_loca
			;;
			"c"|"C")
			echo 0 > uses/$serv_del
			sleep 1
			echo
			echo "Done."
			sleep 1
			redir_loca
			;;
		esac
		;;
		*)
		echo
		echo -e "${rbold}The server you selected was not found. Please try again.$wcol"
		serv_edit
		;;
	esac
	}
	serv_edit
	;;
	"99.3")
	killall openvpn &> /dev/null
	sleep 1
	echo
	echo Done.
	sleep 1
	redir_loca
	;;
	"99.4")
	echo
	echo "Instructions for updating the VPNBook password:"
	echo "1. Go to www.vpnbook.com"
	echo "2. Click the OpenVPN tab"
	echo "3. Enter the password shown on-screen below:"
	echo -n "> " && read vpnbook_pass
	replace "vpnbook_password=$vpnbook_password" "vpnbook_password=$vpnbook_pass" -- "$0" &> /dev/null
	sleep 1
	echo
	echo "Done."
	sleep 1
	redir_loca
	;;
	"99.5")
	echo
	echo 'Do you wish to see the dependency message at start? (Y/N)'
	echo -n "> " && read dep_msg
	case $dep_msg in
		"y"|"Y")
		echo "req-ver-msg: 1" > /opt/au216vpn/dat/dep_msg
		echo
		echo "Done."
		sleep 1
		redir_loca
		;;
		"n"|"N")
		echo "req-ver-msg: 0" > /opt/au216vpn/dat/dep_msg
		echo
		echo "Done."
		sleep 1
		redir_loca
		;;
		*)
		echo foo &> /dev/null
		echo
		echo "Doing nothing..."
		sleep 1.5
		redir_loca
		;;
	esac
	;;
	"99.6")
	echo
	exit
	;;
	"99.7")
	clear
	serv_select
	testing
	;;
	"1.1"|"1")
	echo $(($(cat "uses/11")+1)) > uses/11
	vpnbook_login
	openvpn servers/us1.ovpn
	;;
	"1.2")
	echo $(($(cat "uses/12")+1)) > uses/12
	vpnbook_login
	openvpn servers/us2.ovpn
	;;
	"2.1"|"2")
	echo $(($(cat "uses/21")+1)) > uses/21
	vpnbook_login
	openvpn servers/canada222.ovpn
	;;
	"3.1"|"3")
	echo $(($(cat "uses/31")+1)) > uses/31
	vpnbook_login
	openvpn servers/germany1.ovpn
	;;
	"4.1"|"4")
	echo $(($(cat "uses/41")+1)) > uses/41
	vpnbook_login
	openvpn servers/france1.ovpn
	;;
	"5.1"|"5")
	echo $(($(cat "uses/51")+1)) > uses/51
	vpnbook_login
	openvpn servers/poland226.ovpn
	;;
	"216"|"AU216"|"aU216"|"Au216"|"au216")
	echo
	echo -e "${wtrmrk}You found the Easter Egg!"
	cat "dat/.yay"
	echo
	echo -n -e "${wcol}Press ENTER to continue..." && read null_input
	redir_loca
	;;
	*)
	echo -e "${rbold}Your choice was not recognized. Please try again."
	echo -n -e "${wcol}Press ENTER to continue..." && read null_input
	redir_loca
	;;
esac
}
testing




# Copyright (c) 2018 by Anonymous User 216
#EOF
